// The width of a character in the terminal's cells (R2-4): two for every East_Asian_Width W and F code
// point of the pinned Unicode version, from a table generated by scripts/make-east-asian-width.ts.

import { describe, expect, test } from 'vitest'
import { cellWidth } from '../src/core/tui/cells.js'
import { EAST_ASIAN_WIDTH_VERSION, WIDE_RANGES } from '../src/core/tui/east-asian-width.js'

describe('the generated East Asian Width table', () => {
  test('is Unicode 18.0.0, merged into 126 ranges', () => {
    expect(EAST_ASIAN_WIDTH_VERSION).toBe('18.0.0')
    expect(WIDE_RANGES).toHaveLength(126)
    expect(WIDE_RANGES[0]).toEqual([0x1100, 0x115f])
  })

  test('is sorted, well formed, and merged: no two ranges touch', () => {
    let previousEnd = -2
    for (const [from, to] of WIDE_RANGES) {
      expect(to, `range ${from.toString(16)}`).toBeGreaterThanOrEqual(from)
      expect(from, `range ${from.toString(16)}`).toBeGreaterThan(previousEnd + 1)
      previousEnd = to
    }
  })
})

describe('cellWidth', () => {
  const U = (cp: number): string => String.fromCodePoint(cp)

  test.each([
    ['a Tangut ideograph (U+17000)', 0x17000],
    ['a Yijing hexagram (U+4DC0)', 0x4dc0],
    ['a Kana supplement letter (U+1B000)', 0x1b000],
    ['an enclosed ideographic supplement letter (U+1F210)', 0x1f210],
    ['a Nushu character (U+1B170)', 0x1b170],
    ['a CJK ideograph (U+4E2D)', 0x4e2d],
    ['a Hangul syllable (U+AC00)', 0xac00],
    ['a fullwidth letter (U+FF21)', 0xff21],
    ['an emoji with emoji presentation (U+1F600)', 0x1f600],
  ])('%s is two cells', (_name, cp) => {
    expect(cellWidth(U(cp))).toBe(2)
  })

  test.each([
    ['a letter', 'a'],
    ['an accented letter', 'é'],
    ['a box-drawing character', '─'],
    ['a sun, which is text presentation (U+2600)', '☀'],
  ])('%s is one cell', (_name, text) => {
    expect(cellWidth(text)).toBe(1)
  })

  test('a 40-character Tangut text is 80 cells', () => {
    expect(cellWidth(U(0x17000).repeat(40))).toBe(80)
  })
})
