// The width of a character in the terminal's cells (R2-4): two for every East_Asian_Width W and F code
// point of the pinned Unicode version, from a table generated by scripts/make-east-asian-width.ts.

import { describe, expect, test } from 'vitest'
import { EAST_ASIAN_WIDTH_VERSION, WIDE_RANGES } from '../src/core/tui/east-asian-width.js'

describe('the generated East Asian Width table', () => {
  test('is Unicode 18.0.0, merged into 126 ranges', () => {
    expect(EAST_ASIAN_WIDTH_VERSION).toBe('18.0.0')
    expect(WIDE_RANGES).toHaveLength(126)
    expect(WIDE_RANGES[0]).toEqual([0x1100, 0x115f])
  })

  test('is sorted, well formed, and merged: no two ranges touch', () => {
    let previousEnd = -2
    for (const [from, to] of WIDE_RANGES) {
      expect(to, `range ${from.toString(16)}`).toBeGreaterThanOrEqual(from)
      expect(from, `range ${from.toString(16)}`).toBeGreaterThan(previousEnd + 1)
      previousEnd = to
    }
  })
})
