// Regenerates src/core/tui/east-asian-width.ts from Unicode's EastAsianWidth.txt (R2-4): every code point
// whose East_Asian_Width is W (wide) or F (fullwidth), as merged ranges. A terminal that follows Unicode
// draws each of them in two cells, and the terminal mode counts them so.
//
//   curl -sSL -o tmp/EastAsianWidth.txt https://www.unicode.org/Public/<version>/ucd/EastAsianWidth.txt
//   npm run width-table [-- tmp/EastAsianWidth.txt]
//
// The version is read from the file's first line. test/tui-width.test.ts pins it and the range count, so
// a new Unicode version is a reviewed change (the counts in the test move with it).

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const SOURCE = process.argv[2] ?? 'tmp/EastAsianWidth.txt'
const TARGET = fileURLToPath(new URL('../src/core/tui/east-asian-width.ts', import.meta.url))

const text = readFileSync(SOURCE, 'utf8')
const header = /^# EastAsianWidth-(\d+\.\d+\.\d+)\.txt$/.exec(text.split('\n')[0] ?? '')
if (!header) {
  console.error(`${SOURCE}: the first line is not "# EastAsianWidth-<version>.txt"`)
  process.exit(1)
}
const version = header[1] as string

const rows: [number, number][] = []
for (const raw of text.split('\n')) {
  const data = raw.split('#')[0]?.trim()
  if (!data) continue
  const [range, width] = data.split(';').map((part) => part.trim())
  if (width !== 'W' && width !== 'F') continue
  const [first, last] = (range as string).split('..')
  rows.push([parseInt(first as string, 16), parseInt((last ?? first) as string, 16)])
}
rows.sort((a, b) => a[0] - b[0])

const merged: [number, number][] = []
for (const [from, to] of rows) {
  const previous = merged[merged.length - 1]
  if (previous && from <= previous[1] + 1) previous[1] = Math.max(previous[1], to)
  else merged.push([from, to])
}

const hex = (n: number): string => `0x${n.toString(16)}`
const body = merged.map(([from, to]) => `  [${hex(from)}, ${hex(to)}],`).join('\n')
writeFileSync(
  TARGET,
  `// Generated by scripts/make-east-asian-width.ts from Unicode's EastAsianWidth.txt: do not edit.
// Every code point whose East_Asian_Width is W (wide) or F (fullwidth), as merged ranges: a terminal
// that follows Unicode draws each of them in two cells.

export const EAST_ASIAN_WIDTH_VERSION = '${version}'

export const WIDE_RANGES: readonly (readonly [number, number])[] = [
${body}
]
`
)
console.log(`${TARGET}: Unicode ${version}, ${rows.length} rows merged into ${merged.length} ranges`)
